In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv(r"/content/drive/MyDrive/MN_1/movies.csv")

In [3]:
movies.head()

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [4]:
movies.drop(["Unnamed: 0"],axis = 1,inplace = True)

In [5]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [6]:
movies.shape

(1465, 11)

In [7]:
movies.director_id.nunique()

199

In [8]:
directors = pd.read_csv(r"/content/drive/MyDrive/MN_1/directors.csv")
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [9]:
directors.id.nunique()

2349

In [10]:
np.all(movies["director_id"].isin(directors["id"]))

np.True_

In [11]:
df = movies.merge(directors,left_on = "director_id",right_on = "id",how="left")

In [12]:
df.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,Unnamed: 0,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,0,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,1,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,2,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,3,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,5,Sam Raimi,4767,Male

In [13]:
df.drop(["director_id","Unnamed: 0","id_y"],axis = 1,inplace = True)

In [14]:
df.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [15]:
df.rename({"id_x":"movie_id"},inplace= True,axis = 1)

In [16]:
df.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   object
dtypes: float64(1), int64(6), object(5)
memory usage: 137.5+ KB

In [18]:
df.describe()

,movie_id,budget,popularity,revenue,vote_average,vote_count,year
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465.000000,1465.000000,1465.000000
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,6.368191,1146.396587,2002.615017
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,0.818033,1578.077438,8.680141
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,3.000000,1.000000,1976.000000
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,5.900000,216.000000,1998.000000
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,6.400000,571.000000,2004.000000
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,6.900000,1387.000000,2009.000000
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,8.300000,13752.000000,2016.000000

In [19]:
df.describe(include = "object")

              title month     day     director_name gender
count          1465  1465    1465              1465   1341
unique         1465    12       7               199      2
top     El Mariachi   Dec  Friday  Steven Spielberg   Male
freq              1   193     654                26   1309

In [20]:
df[(df["revenue"]==0) & (df["budget"]==0)]

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
271,44050,0,25,0,The Pink Panther,5.6,550,2006,Jan,Wednesday,Shawn Levy,Male
341,44181,0,13,0,Wolf,6.0,216,1994,Jun,Friday,Mike Nichols,Male
351,44198,0,9,0,Rollerball,3.4,106,2002,Feb,Friday,John McTiernan,NaN
493,44478,0,1,0,Beloved,5.9,26,1998,Oct,Friday,Jonathan Demme,Male
509,44512,0,16,0,Stepmom,6.9,277,1998,Dec,Friday,Chris Columbus,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1453,48294,0,6,0,She's Gotta Have It,6.1,25,1986,Aug,Friday,Spike Lee,Male
1457,48323,0,5,0,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1459,48359,0,2,0,George Washington,6.4,36,2000,Oct,Sunday,David Gordon Green,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male

In [21]:
df.director_name.value_counts().head(10)

director_name
Steven Spielberg     26
Martin Scorsese      19
Clint Eastwood       19
Woody Allen          18
Spike Lee            16
Robert Rodriguez     16
Ridley Scott         16
Renny Harlin         15
Steven Soderbergh    15
Tim Burton           14
Name: count, dtype: int64

In [22]:
df.director_name.value_counts().tail(10)

director_name
Stephen Daldry         5
Gavin O'Connor         5
Mira Nair              5
Sidney Lumet           5
Miguel Arteta          5
Mike Leigh             5
Brad Anderson          5
Michael Polish         5
Darren Lynn Bousman    5
Nicole Holofcener      5
Name: count, dtype: int64

In [23]:
df["revenue"] = (df["revenue"]/1000000).round(2)
df["budget"] = (df["budget"]/1000000).round(2)

In [24]:
df.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.0,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.0,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.0,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [25]:
df["profit"] = df["revenue"] - df["budget"]

In [26]:
df.head()

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,2550.97
1,43598,300.0,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male,661.00
2,43599,245.0,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male,635.67
3,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male,834.94
4,43602,258.0,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male,632.87

In [27]:
df_profitable_directors = df[df["profit"] > 0]

In [28]:
df_profitable_directors.director_name.value_counts().head(10)

director_name
Steven Spielberg     25
Clint Eastwood       16
Ridley Scott         14
Robert Zemeckis      13
Robert Rodriguez     13
Martin Scorsese      13
Michael Bay          12
Steven Soderbergh    12
Tim Burton           12
Joel Schumacher      11
Name: count, dtype: int64

In [29]:
df_profitable_directors.groupby("director_name")["revenue"].mean()

director_name
Adam McKay                     143.180000
Adam Shankman                  116.307143
Alejandro González Iñárritu    146.331667
Alex Proyas                    154.912000
Alexander Payne                102.555000
                                  ...
Wes Craven                      90.707500
Wolfgang Petersen              265.810000
Woody Allen                     76.277500
Zack Snyder                    353.742857
Zhang Yimou                    121.853333
Name: revenue, Length: 194, dtype: float64

In [30]:
def risky_movie_to_do(director_group):
    director_group["risky"] = director_group["budget"] >= director_group["revenue"].mean()
    return director_group

In [31]:
data_risky_directors = df_profitable_directors.groupby("director_name").apply(risky_movie_to_do)

<ipython-input-31-3111784506>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_risky_directors = df_profitable_directors.groupby("director_name").apply(risky_movie_to_do)

In [32]:
data_risky_directors.head(10)

                   movie_id  budget  popularity  revenue  \
director_name
Adam McKay    176     43882   100.0          24   170.43
              323     44151    72.5          12   162.97
              366     44236    65.0          22   128.11
              505     44503    50.0          38   173.65
              839     45301    28.0          57   133.35
              916     45443    26.0          29    90.57
Adam Shankman 265     44040    80.0          23   212.87
              300     44113    50.0          31    90.45
              404     44304    60.0          18   129.18
              458     44404    56.0          35   113.01

                                                         title  vote_average  \
director_name
Adam McKay    176                               The Other Guys           6.1
              323  Talladega Nights: The Ballad of Ricky Bobby           6.2
              366                                Step Brothers           6.5
              505            Anchorman 2: The Legend Continues           6.0
              839                                The Big Short           7.3
              916        Anchorman: The Legend of Ron Burgundy           6.7
Adam Shankman 265                              Bedtime Stories           5.9
              300                                    Hairspray           6.5
              404                       Cheaper by the Dozen 2           5.7
              458                                 The Pacifier           5.8

                   vote_count  year month        day  director_name gender  \
director_name
Adam McKay    176        1383  2010   Aug     Friday     Adam McKay   Male
              323         491  2006   Aug     Friday     Adam McKay   Male
              366        1062  2008   Jul     Friday     Adam McKay   Male
              505         923  2013   Dec  Wednesday     Adam McKay   Male
              839        2607  2015   Dec     Friday     Adam McKay   Male
              916        1493  2004   Jul     Friday     Adam McKay   Male
Adam Shankman 265         901  2008   Dec  Wednesday  Adam Shankman   Male
              300         709  2007   Jul     Friday  Adam Shankman   Male
              404         526  2005   Dec  Wednesday  Adam Shankman   Male
              458         842  2005   Mar     Friday  Adam Shankman   Male

                   profit  risky
director_name
Adam McKay    176   70.43  False
              323   90.47  False
              366   63.11  False
              505  123.65  False
              839  105.35  False
              916   64.57  False
Adam Shankman 265  132.87  False
              300   40.45  False
              404   69.18  False
              458   57.01  False

In [33]:
data_risky_directors["risky"].sum()

np.int64(13)

In [34]:
risky_movies_list = data_risky_directors[data_risky_directors["risky"]==True]

In [35]:
risky_movies_list

                      movie_id  budget  popularity  revenue  \
director_name
David Cronenberg 541     44580    51.5          35    55.11
Frank Oz         193     43916    90.0          19   102.00
Joel Schumacher  128     43807   125.0          50   238.21
Kenny Ortega     852     45315    28.0          18    39.51
Kevin Smith      729     45013    35.0          14    36.10
Louis Leterrier  104     43771   150.0          62   163.71
                 125     43803   125.0          47   232.71
Martin Scorsese  47      43666   170.0          32   185.77
Oliver Stone     69      43709   155.0          39   167.30
Roger Donaldson  144     43837   116.0          16   178.13
Stephen Hopkins  276     44058    80.0          17   136.16
Terry Gilliam    279     44069    88.0          40   105.32
Tom Tykwer       186     43898   102.0          73   130.48

                                    title  vote_average  vote_count  year  \
director_name
David Cronenberg 541     Eastern Promises           7.2         848  2007
Frank Oz         193   The Stepford Wives           5.4         334  2004
Joel Schumacher  128       Batman & Robin           4.2        1418  1997
Kenny Ortega     852          Hocus Pocus           6.4         471  1993
Kevin Smith      729          Jersey Girl           5.8         325  2004
Louis Leterrier  104  The Incredible Hulk           6.1        3021  2008
                 125  Clash of the Titans           5.6        2233  2010
Martin Scorsese  47                  Hugo           7.0        2141  2011
Oliver Stone     69             Alexander           5.6         927  2004
Roger Donaldson  144         Dante's Peak           5.7         428  1997
Stephen Hopkins  276        Lost in Space           5.0         388  1998
Terry Gilliam    279   The Brothers Grimm           5.6         818  2005
Tom Tykwer       186          Cloud Atlas           6.6        2977  2012

                     month       day     director_name gender  profit  risky
director_name
David Cronenberg 541   Sep    Friday  David Cronenberg   Male    3.61   True
Frank Oz         193   Jun  Thursday          Frank Oz   Male   12.00   True
Joel Schumacher  128   Jun    Friday   Joel Schumacher   Male  113.21   True
Kenny Ortega     852   Jul    Friday      Kenny Ortega   Male   11.51   True
Kevin Smith      729   Mar  Thursday       Kevin Smith   Male    1.10   True
Louis Leterrier  104   Jun  Thursday   Louis Leterrier   Male   13.71   True
                 125   Apr  Thursday   Louis Leterrier   Male  107.71   True
Martin Scorsese  47    Nov   Tuesday   Martin Scorsese   Male   15.77   True
Oliver Stone     69    Nov    Sunday      Oliver Stone   Male   12.30   True
Roger Donaldson  144   Feb    Friday   Roger Donaldson   Male   62.13   True
Stephen Hopkins  276   Apr    Friday   Stephen Hopkins   Male   56.16   True
Terry Gilliam    279   Aug    Friday     Terry Gilliam   Male   17.32   True
Tom Tykwer       186   Oct    Friday        Tom Tykwer   Male   28.48   True

In [36]:
risky_movies_list.director_name.value_counts()

director_name
Louis Leterrier     2
David Cronenberg    1
Joel Schumacher     1
Frank Oz            1
Kenny Ortega        1
Kevin Smith         1
Martin Scorsese     1
Oliver Stone        1
Roger Donaldson     1
Stephen Hopkins     1
Terry Gilliam       1
Tom Tykwer          1
Name: count, dtype: int64

In [37]:
risky_movies_list.sort_values(by = "year",ascending = False)

                      movie_id  budget  popularity  revenue  \
director_name
Tom Tykwer       186     43898   102.0          73   130.48
Martin Scorsese  47      43666   170.0          32   185.77
Louis Leterrier  125     43803   125.0          47   232.71
                 104     43771   150.0          62   163.71
David Cronenberg 541     44580    51.5          35    55.11
Terry Gilliam    279     44069    88.0          40   105.32
Oliver Stone     69      43709   155.0          39   167.30
Kevin Smith      729     45013    35.0          14    36.10
Frank Oz         193     43916    90.0          19   102.00
Stephen Hopkins  276     44058    80.0          17   136.16
Joel Schumacher  128     43807   125.0          50   238.21
Roger Donaldson  144     43837   116.0          16   178.13
Kenny Ortega     852     45315    28.0          18    39.51

                                    title  vote_average  vote_count  year  \
director_name
Tom Tykwer       186          Cloud Atlas           6.6        2977  2012
Martin Scorsese  47                  Hugo           7.0        2141  2011
Louis Leterrier  125  Clash of the Titans           5.6        2233  2010
                 104  The Incredible Hulk           6.1        3021  2008
David Cronenberg 541     Eastern Promises           7.2         848  2007
Terry Gilliam    279   The Brothers Grimm           5.6         818  2005
Oliver Stone     69             Alexander           5.6         927  2004
Kevin Smith      729          Jersey Girl           5.8         325  2004
Frank Oz         193   The Stepford Wives           5.4         334  2004
Stephen Hopkins  276        Lost in Space           5.0         388  1998
Joel Schumacher  128       Batman & Robin           4.2        1418  1997
Roger Donaldson  144         Dante's Peak           5.7         428  1997
Kenny Ortega     852          Hocus Pocus           6.4         471  1993

                     month       day     director_name gender  profit  risky
director_name
Tom Tykwer       186   Oct    Friday        Tom Tykwer   Male   28.48   True
Martin Scorsese  47    Nov   Tuesday   Martin Scorsese   Male   15.77   True
Louis Leterrier  125   Apr  Thursday   Louis Leterrier   Male  107.71   True
                 104   Jun  Thursday   Louis Leterrier   Male   13.71   True
David Cronenberg 541   Sep    Friday  David Cronenberg   Male    3.61   True
Terry Gilliam    279   Aug    Friday     Terry Gilliam   Male   17.32   True
Oliver Stone     69    Nov    Sunday      Oliver Stone   Male   12.30   True
Kevin Smith      729   Mar  Thursday       Kevin Smith   Male    1.10   True
Frank Oz         193   Jun  Thursday          Frank Oz   Male   12.00   True
Stephen Hopkins  276   Apr    Friday   Stephen Hopkins   Male   56.16   True
Joel Schumacher  128   Jun    Friday   Joel Schumacher   Male  113.21   True
Roger Donaldson  144   Feb    Friday   Roger Donaldson   Male   62.13   True
Kenny Ortega     852   Jul    Friday      Kenny Ortega   Male   11.51   True

In [38]:
df_profitable_directors

,movie_id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,2550.97
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male,661.00
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male,635.67
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male,834.94
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male,632.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,48321,0.01,20,7.00,Eraserhead,7.5,485,1977,Mar,Saturday,David Lynch,Male,6.99
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male,3.16
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male,0.32
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male,3.12
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN,1.82

In [39]:
productivity_of_directors = df_profitable_directors.groupby("director_name").aggregate({"year":["min","max"],"title":"count"})

In [40]:
productivity_of_directors

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2008     7
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              2002  2013     4
...                           ...   ...   ...
Wes Craven                   1984  2011     8
Wolfgang Petersen            1981  2006     6
Woody Allen                  1977  2013     8
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2011     3

[194 rows x 3 columns]